feat!: Template update to match the widget system.
lenra-io/templates pull request #21
Opened 2022-01-05 09:43 UTC by Nesqwik

2022-01-18 15:20 UTC, jonas-martinez commented on template/node12/index.js
> +app.post('/', middleware);
```suggestion
app.post('/*', middleware);
```

If I properly remember the work on the resources, the star "*" is important so that the middleware catches every resource under every path.
Tell me if I am wrong

2022-01-18 15:20 UTC, jonas-martinez commented on template/node12/index.js
> +app.post('/', middleware);
@shiipou

2022-01-22 21:40 UTC, jonas-martinez requested changes

2022-01-22 21:40 UTC, jonas-martinez commented on template/node12/Dockerfile
> +# COPY function/*.json ./
Why did you comment these lines ?

2022-01-24 08:22 UTC, Nesqwik commented on template/node12/Dockerfile
> +# COPY function/*.json ./
If I remember correctly these are useful for the faas-cli to build the app image for Openfaas.
The `function` directory have been change into the `application` directory for the devtools.

I'm pretty sure these are not needed anymore or at least they must be updated to match old changes we did when we implemented the devtools.

I think we should create a new issue to fix how devtools and openfaas use these template (openfaas might be broken since we started devtools)

2022-01-25 09:06 UTC, taorepoara approved these changes
Seems OK for me.
I'm just not fond of the manifest `entrypoint` attribute, since we will probably have many types of entrypoints in the future.

2022-01-25 09:11 UTC, Nesqwik commented on template/node12/Dockerfile
> +# COPY function/*.json ./
Nevermind i didn't understood what was going on.
The `faac-cli build` when releasing the app on Lenra-CI will create a `function` directory that contain the developper code.
I just changed the process : 
- The dev code will be in the `function` subdirectory inside the template instead of the `application` directory next to the template
- The devtool will be mapped to this `function` subdirectory.
- The server build will copy this `function` subdirectory too.

This simplify the process and avoid copying files from `function` subdir to `application` directory.
The template can point to the `function` directory that is a git submodule of the template-hello-world-node12.

2022-01-25 09:12 UTC, Nesqwik commented
> 

What kind of entrypoint do you have in mind ?

2022-01-25 09:20 UTC, jonas-martinez approved these changes

2022-01-26 08:09 UTC, taorepoara approved these changes
OK.
It's better like that indeed

2022-01-31 08:59 UTC, merged